name: shaiwi_portfolio
description: Shawaiz Niamat — Flutter Developer Portfolio
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # <-- Launcher icons package add ho gaya

# --- App Icon Configuration ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Icon-1024.png" # <-- Aapki image ka path

flutter:
  uses-material-design: true
  assets:
    - assets/images/