// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxnL-zzj-IuWRjIIfiiYnhxk1qBJFvzSY',
    appId: '1:167357954138:web:4af8d4ed31824532a68063',
    messagingSenderId: '167357954138',
    projectId: 'shaiwi-portfolio',
    authDomain: 'shaiwi-portfolio.firebaseapp.com',
    storageBucket: 'shaiwi-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVEVmdZwHaOjmoMytgNFuAzZJ-LPw1MXA',
    appId: '1:167357954138:android:add74de155098425a68063',
    messagingSenderId: '167357954138',
    projectId: 'shaiwi-portfolio',
    storageBucket: 'shaiwi-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw8fm27n4vlA_kS8ZB_Du0242cQ1xrj9U',
    appId: '1:167357954138:ios:24c0014a5963d251a68063',
    messagingSenderId: '167357954138',
    projectId: 'shaiwi-portfolio',
    storageBucket: 'shaiwi-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.shaiwiPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw8fm27n4vlA_kS8ZB_Du0242cQ1xrj9U',
    appId: '1:167357954138:ios:24c0014a5963d251a68063',
    messagingSenderId: '167357954138',
    projectId: 'shaiwi-portfolio',
    storageBucket: 'shaiwi-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.shaiwiPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxnL-zzj-IuWRjIIfiiYnhxk1qBJFvzSY',
    appId: '1:167357954138:web:7a558f1304aa2152a68063',
    messagingSenderId: '167357954138',
    projectId: 'shaiwi-portfolio',
    authDomain: 'shaiwi-portfolio.firebaseapp.com',
    storageBucket: 'shaiwi-portfolio.firebasestorage.app',
  );
}
